import crypto from "node:crypto";

/**
 * Shared by every "email a 6-digit code, verify it later" flow (password reset, admin
 * two-factor, email verification) — the codes are always stored hashed, never in plain
 * text, same reasoning as password hashing but with SHA-256 rather than scrypt: this is
 * high-entropy random data generated by us, not a low-entropy user-chosen secret, so a
 * fast hash is fine. Each flow keeps its own table (different security domains — a bug
 * in one shouldn't let a code leak into another's verification), only this mechanical
 * part is shared.
 */

export function generateSixDigitCode(): string {
  return crypto.randomInt(0, 1_000_000).toString().padStart(6, "0");
}

export function hashCode(code: string): string {
  return crypto.createHash("sha256").update(code).digest("hex");
}
